### ISSUE TITLE
System.write() pops an error

### ISSUE THREAD

**Issue by Oreolek** [sequitur/undum#3]
System.write("text") results in this:

`TypeError: href is undefined`

Firefox traces the error to the second row of:

```
if (!a.hasClass("raw")|| href.match(/[?&]raw[=&]?/)) {
        if (href.match(linkRe)) {
```

**Comment by sequitur** [comment]
1. Which branch are you using (commonjs with Raconteur, I assume?)?
2. Does this bug happen in other branches of the Undum codebase?
3. Is Undum breaking utterly (ie, every single call to System.write fails) or just in the case of one specific call?
4. Does this happen under Webkit (Chrome/Safari)?
5. Can you show us the full situation/function that is causing this?

(This is the relevant code, which is unmodified from baseline Undum:)

``` javascript
/* Returns HTML from the given content with the non-raw links
 * wired up. */
var augmentLinks = function(content) {
    var output = $(content);

    // Wire up the links for regular <a> tags.
    output.find("a").each(function(index, element) {
        var a = $(element);
        var href = a.attr('href'); // !!!
        if (!a.hasClass("raw")|| href.match(/[?&]raw[=&]?/)) {
            if (href.match(linkRe)) {
                a.click(function(event) {
                    event.preventDefault();

                    // If we're a once-click, remove all matching
                    // links.
                    if (a.hasClass("once") || href.match(/[?&]once[=&]?/)) {
                        system.clearLinks(href);
                    }

                    processClick(href);
                    return false;
                });
            } else {
                a.addClass("raw");
            }
        }
    });

    return output;
};
```

**Comment by Oreolek** [comment]
1. Yes, raconteur.
2. It's very hard to test, how do I switch the codebase?
3. Any single call causes situation content function to fail.
4. Hmm. It's weird but no, Chrome works okay with that.
5. I've tried it in many functions and any call to System.write works like this.

**Comment by sequitur** [comment]
Does normal situation content writing work? Raconteur itself calls System.write to do this.

Can you post your full source code?

**Comment by Oreolek** [comment]
Yes, the returns work. So for example: 

```
response = oneOf(
  "Hello."
  "Hi.
).randomly(system)
system.write(response)
```

must be written as:

```
response = oneOf(
  "Hello."
  "Hi.
).randomly(system)
"""
#{response}
"""
```

This style can be troublesome if you have a lot of dynamic content in the situation.

**Comment by sequitur** [comment]
Yeah, I can't reproduce this specific error at all, either under Chrome or under Firefox 41.

Three things, however.
1. system.write expects valid HTML. So, `system.write("Hello.")` will throw an error, and you shouldn't expect other calls in that vein to work either. When you call `system.write`, you should give it valid HTML (ie, the entire output should be wrapped in start and end tags such as `<span>`or `<p>`) otherwise it could throw any number of JQuery errors.
2. Calls to things like system.write() from inside content() functions is unsupported functionality. It might work, but you're supposed to use after() or before() functions instead to output content imperatively.
3. oneOf closure objects are functions, not strings, so passing them to system.write will definitely not work; you should call them (they output a string) or stringify them (they stringify to their own output) first.

**Comment by Oreolek** [comment]
Yes, it was invalid HTML problem. Thank you.
